
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: 7777777
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

# mybatis 日志打印
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

projectUrl:
  wechatMpAuthorize: http://aa71ac1dc2ae.ngrok.io
  wechatOpenAuthorize: http://aa71ac1dc2ae.ngrok.io
  sell: http://aa71ac1dc2ae.ngrok.io

wechat:

  # 公众账号, 授权
  mpAppId: wxf396eb9a06068e29
  mpAppSecret: fc728a1bd0826af24e24ed37182f46f6

  # 开放平台,  卖家扫码登录用
  openAppId: wxf396eb9a06068e29
  openAppSecret: fc728a1bd0826af24e24ed37182f46f6

